In [3]:
import numpy as np
import quaternion # using numpy-quaternion not Quaternion
import math
from URutility import *
from scipy.spatial.transform import Rotation as R
from UtilTrans import *

a=[1,2,3]
b=[4,5,6]
x,y,z=a

0.1*np.array(a+b)
Kxx = np.diag([10, 10, 10])
Kxr = np.zeros((3,3))
Krx = Kxr
Krr = np.diag([10, 10, 10])
Krr,Krx,Kxx,Kxr
Smat = np.vstack((np.hstack((Kxx, Kxr)), np.hstack((Kxr, Krr))))
FT = np.array(6*[3])
FT.dot(Smat), FT
# should in xyzw form
r = R.from_quat([0.7041204401734303, -0.1279943122329314, -
                0.6964914805048041, -0.052263556616629236]) 
print('rotation:\n',r.as_matrix())
a = [-2.4878, 4.5537, -7.0339, 0.0364, 0.2155, -0.08]
b = [1.976, 1.273, 2.0045, -0.0675, 0.0057, -0.0399]
c = [a,b]
np.average(np.array(c), axis=0).tolist()
np.sum(np.array(a) < np.array(b))
10 * np.array([0.1, 0.1, 0.1, 0.001, 0.001, 0.001])
# sum(c)
np.abs(a)
5//2
trace_arg(",11",",22",",33")
a1=np.array([1,2,3])
b1 = np.array([-1,1,1])
a1*b1

rotation:
 [[-0.00296585 -0.25304907 -0.9674489 ]
 [-0.10744458 -0.96177195  0.25189357]
 [-0.99420665  0.10469422 -0.02433628]]
,11 ,22 ,33


array([-1,  2,  3])

## pyquaternion
refer: http://kieranwynn.github.io/pyquaternion/
1. quaternion definition using list, and trans to list
2. quaternion definition using axis rotation
3. quaternion differential from quaternion with angular velocity
4. quaternion  q0 and qr obtain
5. quaternion substract and dot product(rotation between 2 frames)
6. quaternion inverse and normalization

In [14]:
import numpy as np
from pyquaternion import Quaternion
from URutility import *

### 1. quaternion definition
qu1 = Quaternion(axis=[1, 0, 0], angle=3.14159265)
qu2 = Quaternion(1, 1, 0, 0) # or list or tuple, w,x,y,z order
qu3 = Quaternion(np.array([3,4,5,6]))
qu4 = qu2.normalised
rotation = np.eye(3)
transformation = np.eye(4)
q8d = Quaternion(matrix=rotation) # Using 3x3 rotation matrix
q8dr = Quaternion(matrix=transformation) # Using 4x4 transformation matrix
my_quaternion = qu2
qu2 = Quaternion(vector=[0, 1, 0])
r = my_quaternion.scalar
v = my_quaternion.vector
my_quaternion[2] = 2
a = my_quaternion.elements
print("{} + {}i + {}j + {}k".format(a[0], a[1], a[2], a[3]))
str(my_quaternion)

### 2. quaternion math
#### conjugate, normalise and inverse, rotate in xyz, to rotation matrix, bool
unit_qu2 = qu2.normalised
conj_qu2 = qu2.conjugate
inv_qu2 = qu2.inverse
norm_my_quaternion = my_quaternion.norm # L2 norm
rotated_list = my_quaternion.rotate([1.0, 0.0, 0.0])  # Returns a list
rotated_array = my_quaternion.rotate(np.array(
    [1.0, 0.0, 0.0]))  # Returns a Numpy 3-array
R = my_quaternion.rotation_matrix         # 3x3 rotation matrix
print("R",R)
T = my_quaternion.transformation_matrix   # 4x4 transformation matrix
Quaternion(scalar=0.0) == False
Quaternion(1, 0, 1, 1) == Quaternion(scalar=1.0, vector=[0.0, 1.0, 1.0])
# Numpy array of individual elements
my_elements = my_quaternion.elements
-my_quaternion == Quaternion(-my_elements)
qu1 + qu2
qu1 - qu2
qu1 * qu2  # is the quaternion formed by Hamilton product of q1 and q2. Source The Hamiltonian product is not commutative http://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/arithmetic/index.htm
qu1 / qu2 # is the quaternion formed by Hamilton product of q1 and q2.inverse()
qu1**2 # pow 2

### 3. quaternion motion transformation
#### differentiation
# Rotate about z at 0.5 rotation per second
q_dot = qu2.derivative([0, 0, 3.14159])
#### integrate with axis speed and timestep
q9 = Quaternion()  # null rotation
q9.integrate([2*math.pi, 0, 0], 0.25)  # Rotate about x at 1 rotation per second, axis xyz angular velocity , other is the timestep
q9 == Quaternion(axis=[1, 0, 0], angle=(math.pi/2))
#### change a vector
v = np.array([0., 0., 1.])  # Unit vector in the +z direction
v_prime = my_quaternion.rotate(v) # define a vector and use the quaternion rotation change the vector to target
#### insert rotation quaternion in q0 and q1, and insert points with these quaternions ########
v = np.array([0., 0., 1.])  # Unit vector in the +z direction
q0 = Quaternion(axis=[1, 1, 1], angle=0.0)  # Rotate 0 about x=y=z
# Rotate 120 about x=y=z
q1 = Quaternion(axis=[1, 1, 1], angle=2 * 3.14159265 / 3)
for q in Quaternion.intermediates(q0, q1, 8, include_endpoints=True):
    v_prime = q.rotate(v)
    print(v_prime)
########

# trace_arg(qu1,qu2,qu3, qu4,q8d,q8dr)
qu1, qu2, qu3, qu4, q8d, q8dr
unit_qu2,conj_qu2,inv_qu2,norm_my_quaternion
rotated_list,my_quaternion
q_dot


1.0 + 1.0i + 2.0j + 0.0k
R [[-0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.66666667 -0.33333333]
 [-0.66666667  0.33333333 -0.66666667]]
[0. 0. 1.]
[ 0.14213118 -0.12416109  0.98202991]
[ 0.29457011 -0.22365854  0.92908843]
[ 0.44909878 -0.29312841  0.84402963]
[ 0.59738651 -0.32882557  0.73143906]
[ 0.73143906 -0.32882557  0.59738651]
[ 0.84402963 -0.29312841  0.44909879]
[ 0.92908843 -0.22365854  0.29457012]
[ 0.98202991 -0.12416109  0.14213118]
[ 1.00000000e+00 -1.38171186e-09  1.38171186e-09]


Quaternion(0.0, 1.570795, 0.0, 0.0)

In [15]:
import numpy as np
import quaternion  # using numpy-quaternion not Quaternion
from UtilTrans  import *
q1 = np.quaternion(-0.031, 0.680, 0.017, 0.733)
q2 = np.quaternion(-0.061, 0.686, 0.045, 0.723)
q_from_tf = np.array([-0.130, -0.653, -0.046, 0.745])
print(quaternion2axisangle(q_from_tf))
q1.inverse()
delta_q = q2*q1.inverse()  # target 2, from 1 to 2, base to 0
print(delta_q)
q = [q2.w*q1.x - q1.w*q2.x, q2.w*q1.y - q1.w*q2.y, q2.w*q1.z - q1.w*q2.z]
s = skew([q1.x, q1.y, q1.z])
d2 = np.array(q) - s.dot([q2.x, q2.y, q2.z])
d2, q1.w
q1 = np.quaternion(1, 2, 3, 4) # w,x,y,z
q1.normalized()
quaternion.as_rotation_matrix(q1)
pos = [1,0,0,30.0,0,0]
euler_l = [i/180.0*math.pi for i in pos[3:]]
q2=quaternion.from_euler_angles(euler_l)
q1
q2
q2-q1,q1.w

q2.tolist().T

[1.8972986029149108, 0.13365350035847764, -2.1646056036318657]
quaternion(0.998157729891632, -0.000479549702829044, 0.0108298307888893, 0.0411993138443002)


quaternion(0.965925826289068, -0, 0, 0.258819045102521)

In [16]:
import sophus as sp
R = sp.SO3([[0, 1, 0],
            [0, 0, 1],
            [1, 0, 0]])
R

SO3([[0, 1, 0],
     [0, 0, 1],
     [1, 0, 0]])

In [20]:
from UtilTrans import *
l1 = [5,4,3,6,2]
s=""
# [s+str(i)+"," for i in l1]
','.join(map(str,l1))
# l1.pop(0)
# l1
a=2
l1[-a:]
l1.sort()
l1[:-1]
# def x(a):
np.array(l1)[2]
a1 = [ -0.2846885, -1.5490346, -0.1162675 ]
a2 = [0.8479, 4.6139, 0.3463]
b2 = [-1.598, -1.463, 1.342]
b1 = [-0.2561919, -0.1076444, -1.5738151 ]
np.array(a2)/np.array(a1)
np.array(b2)-np.array(b1)
# list_minus(a1,b1)

NameError: name 'list_minus' is not defined

In [33]:
from UtilTrans import *
a1 = [ -0.2846885, -1.5490346, -0.1162675 ]
a2 = [0.8479, 4.6139, 0.3463]
b2 = [-1.598, -1.463, 1.342]
b1 = [-0.2561919, -0.1076444, -1.5738151 ]
c=np.array(a2)/np.array(a1)
c1=np.insert(c,3,[0,0,0])
c,c1
0.0*np.array([1e8, 1e8, 1e8, 5, 5, 5])
# np.array(b2)-np.array(b1)
# list_minus(a1,b1)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
x1 =[0.9405, 4.6809, 0.3291]
[i/3.14*180 for i in x1]

[53.91401273885349, 268.33184713375795, 18.8656050955414]

In [ ]:
# import tkinter as tk
# from tkinter import ttk

# def ok_click():
#     pass

# def clear_click():
#     pass

# root = tk.Tk()
# # lab1 = tk.Label(root, width=5, height=)
# txt1 = tk.Text(root, width=50, height=20)
# txt1.pack(padx=5, pady=5)
# lab2 = tk.Label(root, width=5, height=5)
# txt2 = tk.Text(root, width=30, height=5)
# ok_btn = ttk.Button(root, text="ok", command=ok_click)
# clear_btn = ttk.Button(root, text="clear", command=clear_click)

# txt1.grid(column=0, row=0, columnspan=2)           # 放置按钮
# txt2.grid(column=0, row=1, columnspan=1)
# ok_btn.grid(column=0, row=2)
# clear_btn.grid(column=1, row=2)

# # # 设置文本格式tag
# # text1.tag_config('tag_1', background='yellow',
# #                 foreground='red')  # bg,fg 并不是它的缩写

# # insert 索引表示插入光标的当前位置，并可以设置文本格式
# txt1.insert('insert', '我今天想吃')  # 在光标位置插入
# # text1.insert('end', '麻辣小龙虾', 'tag_1')  # 在最后位置插入

# root.mainloop()


In [ ]:
import re
a = "force:     x: 0.7695000171661377    y: 2.0139999389648438    z: -0.968999981880188  torque:     x: 0.015200000256299973    y: 0.033250000327825546    z: -0.04749999940395355"
a = " position: [0.8203511238098145, -0.9432128111468714, -0.0330122152911585, -3.0166876951800745, 4.486150741577148, -1.4653261343585413]"
re.split("\s*[;,\s,\[,\]]\s*", a)


In [ ]:

# import tkinter as tk
# import tkinter.ttk as ttk

# win = tk.Tk()
# win.title("CommunicationTool")
# #setting
# setFrame = tk.LabelFrame(win, text="Setting")
# comFrame = tk.Frame(setFrame)
# comLable = tk.Label(comFrame, text="COM Port: ").pack(side=tk.LEFT)
# comSpiner = tk.Spinbox(comFrame, text="COM1").pack(side=tk.LEFT)
# refrashButton = ttk.Button(comFrame, text="Refresh").pack(side=tk.LEFT)
# comFrame.pack(anchor=tk.W)
# cmdFrame = tk.Frame(setFrame)
# inputLable = tk.Label(cmdFrame, text="Command: ").pack(side=tk.LEFT)
# inputEntry = tk.Entry(cmdFrame).pack(side=tk.LEFT, expand=1, fill=tk.X)
# sendButton = ttk.Button(cmdFrame, text="Send").pack(side=tk.LEFT)
# cmdFrame.pack(anchor=tk.W, expand=1, fill=tk.X)
# setFrame.pack(fill=tk.BOTH)
# #output
# outputFrame = tk.LabelFrame(win, text="Output")
# area = tk.Text(outputFrame).pack(expand=1, fill=tk.BOTH)
# outputFrame.pack(expand=1, fill=tk.BOTH)

# win.mainloop()


In [ ]:
from URutility import *
from UtilTrans import *
a=[1.2,3.4]
[float("%.4f" % float(i)) for i in a]
F_d = [-8.5215, 14.041, -33.782, -0.9937, 0.797, 0.5795]
force_measure_to_in_force_frame(np.array(F_d))

[8.5215, -14.041, 33.782, 0.9937, -0.797, -0.5795]

In [ ]:
from cvxopt import matrix, solvers
import numpy as np
from sympy import  *
import cvxpy as cp
print(cp.installed_solvers())

A = matrix([[-1.0, -1.0, 0.0, 1.0], [1.0, -1.0, -1.0, -2.0]])
b = matrix([1.0, -2.0, 0.0, 4.0])
c = matrix([2.0, 1.0])

sol = solvers.lp(c, A, b)

print(sol['x'])
print(np.dot(sol['x'].T, c))
print(sol['primal objective'])


['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']
     pcost       dcost       gap    pres   dres   k/t
 0:  2.6471e+00 -7.0588e-01  2e+01  8e-01  2e+00  1e+00
 1:  3.0726e+00  2.8437e+00  1e+00  1e-01  2e-01  3e-01
 2:  2.4891e+00  2.4808e+00  1e-01  1e-02  2e-02  5e-02
 3:  2.4999e+00  2.4998e+00  1e-03  1e-04  2e-04  5e-04
 4:  2.5000e+00  2.5000e+00  1e-05  1e-06  2e-06  5e-06
 5:  2.5000e+00  2.5000e+00  1e-07  1e-08  2e-08  5e-08
Optimal solution found.
[ 5.00e-01]
[ 1.50e+00]

[[2.49999999]]
2.4999999895543077


In [10]:
from UtilTrans import *

v = [0,0, 1.5,-1.5, 0.8, 0.002]
v = V_d_limitation(v)
v

[0.0, 0.0, 0.5, 0.3, 0.4, 0.5]